
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package projetoPT3;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int AbreCochetes = 9;
  public static final int deu = 24;
  public static final int Cadeia_de_Caracteres = 15;
  public static final int mult = 18;
  public static final int FechaChaves = 8;
  public static final int FechaCochetes = 10;
  public static final int exp = 20;
  public static final int inteiro = 13;
  public static final int Maior = 21;
  public static final int compIg = 23;
  public static final int Zint = 3;
  public static final int AbreChaves = 7;
  public static final int flutuante = 14;
  public static final int cf = 6;
  public static final int div = 19;
  public static final int add = 16;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Id = 2;
  public static final int FechaParentese = 12;
  public static final int subt = 17;
  public static final int Menor = 22;
  public static final int Txt = 5;
  public static final int efvLoop = 26;
  public static final int Rfloat = 4;
  public static final int deuN = 25;
  public static final int Att = 27;
  public static final int AbreParentese = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Id",
  "Zint",
  "Rfloat",
  "Txt",
  "cf",
  "AbreChaves",
  "FechaChaves",
  "AbreCochetes",
  "FechaCochetes",
  "AbreParentese",
  "FechaParentese",
  "inteiro",
  "flutuante",
  "Cadeia_de_Caracteres",
  "add",
  "subt",
  "mult",
  "div",
  "exp",
  "Maior",
  "Menor",
  "compIg",
  "deu",
  "deuN",
  "efvLoop",
  "Att"
  };
}

